DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS CUSTOMERS;

CREATE TABLE IF NOT EXISTS PRODUCT(
PRODUCT_ID TEXT PRIMARY KEY,
PRODUCT_NAME TEXT,
PRICE REAL
);

CREATE TABLE IF NOT EXISTS CUSTOMERS(
CUSTOMER_ID TEXT PRIMARY KEY,
CUSTOMER_NAME TEXT,
CITY TEXT,
AGE INTEGER,
PRODUCT_NAME TEXT,
QUANTITY INTEGER
);

INSERT INTO PRODUCT VALUES
('1', 'LAPTOP', 1000.0),
('2', 'IPHONE', 800.0),
('3', 'TABLET', 600.0);

INSERT INTO CUSTOMERS VALUES
('1', 'JOHN DOE', 'NEW YORK', 30, 'LAPTOP', 1),
('2', 'FATIMA ALI', 'LOS ANGELES', 21, 'IPHONE', 1),
('3', 'ORLANDO SMITH', 'CHICAGO', 45, 'TABLET', 45);

SELECT * FROM PRODUCT;
SELECT * FROM CUSTOMERS;

SELECT * FROM CUSTOMERS WHERE CUSTOMER_NAME LIKE "%A%";
SELECT * FROM CUSTOMERS WHERE CUSTOMER_NAME LIKE "%OR%";