CREATE TABLE EMPLOY (
ID TEXT PRIMARY KEY,
NAME TEXT,
AGE INTEGER,
GENDER TEXT,
DEGREE TEXT
);

INSERT INTO EMPLOY VALUES ('1', 'JACK', 20, 'MALE', 'YES');
INSERT INTO EMPLOY VALUES ('2', 'JANE', 25, 'FEMALE', 'YES');
INSERT INTO EMPLOY VALUES ('3', 'ROBERT', 30, 'MALE', 'NO');
INSERT INTO EMPLOY VALUES ('4', 'EMILY', 22, 'FEMALE', 'YES');
INSERT INTO EMPLOY VALUES ('5', 'DAVID', 28, 'MALE', 'NO');

SELECT * FROM EMPLOY;


SELECT * FROM EMPLOY WHERE DEGREE = 'YES';
SELECT * FROM EMPLOY WHERE DEGREE = 'NO';