CREATE TABLE CUSTOMERS (
Identify TEXT PRIMARY KEY,
Name TEXT,
Grade INTEGER,
City TEXT
    
);

INSERT INTO CUSTOMERS VALUES ('1', 'RAM', 203, 'NEW YORK');
INSERT INTO CUSTOMERS VALUES ('2', 'JAY', 97, 'NEW YORK');
INSERT INTO CUSTOMERS VALUES ('3', 'STEVEN', 103, 'LONDON');
INSERT INTO CUSTOMERS VALUES ('4', 'JOHN', 150, 'LONDON');
INSERT INTO CUSTOMERS VALUES ('5', 'JACK', 120, 'NEW YORK');

SELECT * FROM CUSTOMERS;

SELECT * FROM CUSTOMERS WHERE Grade > 100 AND City = 'NEW YORK';
SELECT * FROM CUSTOMERS WHERE Grade > 100
SELECT * FROM CUSTOMERS WHERE City = 'NEW YORK';
SELECT * FROM CUSTOMERS WHERE City = 'LONDON';