# Assignin different variables
name = "penguin"
age = 15
weight = 35.5
is_student = True
# Printiing different types of variables
print("Name:", name)
print("Data typr is:", type(name))
      
print("Age:", age)
print("Data type is:", type(age))

print("is_student:", is_student)
print("Data type is:", type(is_student))

print("Weight:", weight)
print("Data type is:", type(weight))

# Type casting to convert data types
print("\n After Type casting:")
age = str(age)
print(age)
print(type(age))
weight = int(weight)
print(weight)
print(type(weight))

age = (age)
print(age)
print(type(age))