CREATE TABLE IF NOT EXISTS MARKS (
ID INT PRIMARY KEY,
NAME TEXT,
SUBJECT TEXT,
MARK INT);

INSERT INTO MARKS (ID, NAME, SUBJECT, MARK) VALUES
(1, 'Alice', 'Math', 85),
(2, 'Bob', 'Math', 90),
(3, 'Charlie', 'Math', 78),
(4, 'Alice', 'Science', 92),
(5, 'Bob', 'Science', 88),
(6, 'Charlie', 'Science', 80);

SELECT * FROM MARKS;

SELECT DISTINCT(NAME) AS Distinct_Data FROM MARKS;

SELECT COUNT(ID) AS STUDENT_COUNT FROM MARKS;

SELECT AVG(MARK) AS AVG_MARK FROM MARKS;

SELECT SUM(MARK) AS TOTAL_MARKS FROM MARKS;
