a = 12
b = 6
c = 0
if a and b and c:
    print("All variable have boolean value true")
else:
    print("At least one variable has boolean value false")

    a = 10
    b = -10
    c = 0

    if a > 0 or b > 0:
        print("At least one variable is positive")
    else:
        print("All variables are negative or zero")

    if b > 0 or c > 0:
        print("At least one variable is positive")
    else:
        print("All variables are negative or zero")