DROP TABLE IF EXISTS DEPARTMENT;

CREATE TABLE DEPARTMENT (

EMP_ID TEXT PRIMARY KEY,

NAME TEXT,

DEP_ID TEXT,

MANG_ID TEXT,

SALARY REAL

);

INSERT INTO DEPARTMENT (EMP_ID, NAME, DEP_ID, MANG_ID, SALARY) VALUES

('1', 'STEVEN KING', '90', '100', 24000),

('2', 'NEENA KOCHAR', '90', '100', 17000),

('3', 'LEX DE HAGE', '90', '100', 17000),

('4', 'ALEXANDER HUNOLD', '60', '102', 9000),

('5', 'BRUCE ERNST', '60', '102', 6000),

('6', 'DAVID AUSTIN', '60', '102', 4800);

SELECT DEP_ID AS "Department Code",

COUNT(*) AS "No of Employees"

FROM DEPARTMENT

GROUP BY DEP_ID;

SELECT DEP_ID,

SUM(SALARY) AS "Total Salary"

FROM DEPARTMENT

GROUP BY DEP_ID;

SELECT DEP_ID AS "Department Code",

COUNT(*) AS "No of Employees",

SUM(SALARY) AS "Total Salary"

FROM DEPARTMENT

GROUP BY DEP_ID;

SELECT DEP_ID AS "Department Code",

SUM(SALARY) AS "Total Salary"

FROM DEPARTMENT

WHERE MANG_ID = '100'

GROUP BY DEP_ID;

SELECT DEP_ID,

COUNT(*) AS "No. of Employees"

FROM DEPARTMENT

GROUP BY DEP_ID

HAVING COUNT(*) > 2;