DROP TABLE IF EXISTS NEWS;

CREATE TABLE NEWS (
    HACK_ID INT PRIMARY KEY,
    NAME TEXT,
    CATEGORY TEXT,
    VIEWS INT,
    RANSOM_FEE REAL
);

INSERT INTO NEWS VALUES (1, 'Hacker One', 'Cybersecurity', 1000, 50000);
 INSERT INTO NEWS VALUES (2, 'Hacker Two', 'Cybersecurity', 1500, 75000);
 INSERT INTO NEWS VALUES (3, 'Hacker Three', 'Cybersecurity', 2000, 100000);
  INSERT INTO NEWS VALUES (4, 'Hacker Four', 'Cybersecurity', 2500, 1250000);
   INSERT INTO NEWS VALUES (5, 'Hacker Five', 'Cybersecurity', 3000, 150000);
    INSERT INTO NEWS VALUES (6, 'Hacker Six', 'Cybersecurity', 3500, 175000);
SELECT CATEGORY AS "NUMBER OF HACKERS", COUNT(*) AS "HACKER COUNT" FROM NEWS GROUP BY CATEGORY;

SELECT * FROM NEWS ORDER BY RANSOM_FEE ASC;

SELECT SUM(RANSOM_FEE) AS "TOTAL FEE" FROM NEWS;

SELECT * FROM NEWS GROUP BY VIEWS ORDER BY VIEWS DESC;