CREATE TABLE IF NOT EXISTS STUDENT (
    ROLL_NO TEXT PRIMARY KEY,
    NAME TEXT,
    ADDRESS TEXT,
    PHONE TEXT,
    AGE INTEGER
);

INSERT INTO STUDENT VALUES ('1', 'RAM', 'DEHLI', '19283', 18);
INSERT INTO STUDENT VALUES('2', 'JAY', 'UNITED KINGDOM', '19283', 19);
INSERT INTO STUDENT VALUES('3', 'STEVEN', 'CHINA', '19283', 18);
INSERT INTO STUDENT VALUES('4', 'JOHN', 'UNITED STATES', '19283', 20);
INSERT INTO STUDENT VALUES('5', 'JACK', 'CANADA', '19283', 20);
INSERT INTO STUDENT VALUES('6', 'ISIAH', 'DEHLI', '19283', 19);

SELECT * FROM STUDENT;

SELECT * FROM STUDENT WHERE AGE = 18 AND ADDRESS = 'DEHLI';

SELECT * FROM STUDENT WHERE AGE = 18 AND ADDRESS = 'CHINA';

SELECT * FROM STUDENT WHERE AGE = 20 OR ADDRESS = 'DEHLI';

SELECT * FROM STUDENT WHERE AGE = 19 OR ADDRESS = 'UNITED STATES';

SELECT * FROM STUDENT WHERE AGE = 19 AND (NAME = 'RAM' OR 'NAME'
= 'JAY'); 